### ISSUE TITLE
I found a typo in the README

### ISSUE THREAD

**Issue by jama-ica** [Cysharp/MasterMemory#26]
```yml
- run: dotnet mmgen -i ./ -o ./MasterMemory -m Test
↓
- run: dotnet mmgen -i ./ -o ./MasterMemory -n Test
```
